name: Package smindex

on:
  push:
  workflow_dispatch:
    inputs:
      run_tests:
        type: boolean
        description: 'Run tests after packaging'
        required: false
        default: true

run-name: Build and test smindex package

jobs:
  package:
    runs-on: ubuntu-latest
    name: Build and test package
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

    - name: Set up Python
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        python3 -m venv env
        source env/bin/activate
        pip install setuptools wheel pytest

    - name: Build package
      run: |
        source env/bin/activate
        python3 setup.py bdist_wheel

    - name: Upload package artifact
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
      with:
        name: smindex-package
        path: dist/

    - name: Run tests
      if: ${{ github.event.inputs.run_tests == 'true' || github.event_name == 'push' }}
      run: |
        export SMINDEX_PATH="$(pwd)/.data"
        mkdir -p $SMINDEX_PATH
        cat >$SMINDEX_PATH/config.json <<EOF
        {
            "username": "${{ secrets.USERNAME }}",
        }
        EOF
        source env/bin/activate
        pip install -r requirements.txt
        pip install dist/smindex-*.whl
        cd tests
        pytest .
